name = "mornigdock"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = [ "nodejs_compat" ]

[define]
"process.env.WORKER" = '"true"'

[triggers]
crons = [ "0 * * * *" ]

[vars]
NODE_ENV = "production"
WORKER = "true"

[assets]
directory = "../frontend/dist"
binding = "ASSETS"